insert into BOOK_TBL (id, name, author, price, is_Recommended) values (1, 'Harry Potter1', 'J.K.Rolling', 123.45, true )
insert into BOOK_TBL (id, name, author, price, is_Recommended) values (2, 'Harry Potter2', 'J.K.Rolling', 4445.56, true)
insert into BOOK_TBL (id, name, author, price, is_Recommended) values (3, '3Harry Potter2', 'J.K.Rolling', 4445.56, true)
insert into BOOK_TBL (id, name, author, price, is_Recommended) values (4, 'Harry Potter3', 'J.K.Rolling', 4445.56, false)
insert into BOOK_TBL (id, name, author, price, is_Recommended) values (5, '1Harry Potter3', 'J.K.Rolling', 4445.56, false)
